# Change these first
owner: GuillemAcero # Your GitHub organization or username, where this repository lives
repo: upptime-test # The name of this repository

sites:
  - name: Doofinder
    url: https://www.doofinder.com
  - name: Ngrok Test
    url: https://smoothly-main-raccoon.ngrok-free.app/
  - name: Fail URL
    url: http://noexistpage123.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-test
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Doofinder Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "This is a test message for the doofidner status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
